### ISSUE TITLE
Pydantic import error

### ISSUE THREAD

**Issue by osma** [iscc/iscc-core#125]
It seems that the package is incompatible with recent changes in Pydantic. I just installed `iscc-core` into a fresh Python 3.10 venv and then tried to import it. This was the result:

```
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import iscc_core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/proj/iscc/venv/lib/python3.10/site-packages/iscc_core/__init__.py", line 2, in <module>
    from iscc_core.options import core_opts, conformant_options
  File "/home/xxx/proj/iscc/venv/lib/python3.10/site-packages/iscc_core/options.py", line 15, in <module>
    from pydantic import BaseSettings, Field
  File "/home/xxx/proj/iscc/venv/lib/python3.10/site-packages/pydantic/__init__.py", line 363, in __getattr__
    return _getattr_migration(attr_name)
  File "/home/xxx/proj/iscc/venv/lib/python3.10/site-packages/pydantic/_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.5/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.5/u/import-error
```

There is currently no version restriction defined for the Pydantic dependency: https://github.com/iscc/iscc-core/blob/fb114bbaa8c02a8dabb8bb5f691a76aeb6a2b9c3/pyproject.toml#L50 

The packages that were automatically installed by pip are:

```
Package           Version
----------------- -------
annotated-types   0.6.0
base58            2.1.1
bitarray          2.8.5
blake3            0.3.4
data-url          1.0.7
iscc-core         1.0.5
jcs               0.2.1
loguru            0.7.2
more-itertools    10.1.0
pip               22.0.2
pybase64          1.3.1
pydantic          2.5.2
pydantic_core     2.14.5
setuptools        59.6.0
typing_extensions 4.9.0
uvarint           1.2.0
xxhash            3.4.1

```

The solution for this and similar issues is to specify more specific version requirements for dependencies.

**Comment by titusz** [comment]
Hi @osma, you are right! This did not fail in CI because the dev dependencies include iscc-schema which has a pinned Pydantic dependency. Thanks for reporting this. I will fix the issue and see how I can update the CI to catch these kind of dependency issues in the future.

**Comment by titusz** [comment]
I fixed the issue and added wheel installation testing to CI. New release 1.0.6 is available on pypi. Let me know if this fixes your issue.

**Comment by titusz** [comment]
As a note: The dependencies for the `iscc-core` package as distributed on PYPI are not strictly pinned. This allows it to be used together with other libraries that might depend on specific versions of the same dependencies. Nevertheless, there is a `poetry.lock` file **that pins dependencies** and allows for reproducible installation in a development environment as follows:

```shell
git clone https://github.com/iscc/iscc-core.git
cd iscc-core
poetry install
```
